application:
  name: clockin-sacha-house
  port: 3000
  healthPath: /api/health

modules:
  task:
    - deploy/task.hcl

environments:
  staging:
    domain: staging.clockin.sacha.house
    noIndex: true
  production:
    domain: clockin.sacha.house

    modules:
      group:
        - deploy/group-production.hcl
volume:
  mountPath: /data

resources:
  cpu: 500
  memory: 512
