application:
  name: clockin-sacha-house
  port: 3000
  healthPath: /api/health

environments:
  staging:
    domain: staging.clockin.sacha.house
    noIndex: true
    modules:
      task:
        - deploy/task-staging.hcl
  production:
    domain: clockin.sacha.house

    modules:
      group:
        - deploy/group-production.hcl
      task:
        - deploy/task-production.hcl
volume:
  mountPath: /data

resources:
  cpu: 500
  memory: 512
